services:
  - type: web
    name: faraday-ai
    runtime: python
    region: oregon
    plan: pro-4gb
    buildCommand: |
      python3.10 -m pip install -r requirements.txt
      
      # Create models and logs directory structure
      echo "Creating directory structure..."
      mkdir -p /app/models
      mkdir -p /tmp/faraday-ai/logs
      chmod -R 777 /tmp/faraday-ai/logs
      
      # Create placeholder models
      echo "Creating placeholder models..."
      python3.10 -c "
      import tensorflow as tf
      import joblib
      import numpy as np
      import logging
      import os
      
      # Configure logging
      logging.basicConfig(
          level=logging.INFO,
          format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
          handlers=[
              logging.FileHandler('/tmp/faraday-ai/logs/model_creation.log'),
              logging.StreamHandler()
          ]
      )
      logger = logging.getLogger(__name__)
      
      try:
          # Create movement analysis model
          logger.info('Creating movement analysis model...')
          model = tf.keras.Sequential([
              tf.keras.layers.Dense(10, activation='relu', input_shape=(10,)),
              tf.keras.layers.Dense(1, activation='sigmoid')
          ])
          model.save('/app/app/models/movement_analysis_model.keras', save_format='keras')
          logger.info('Movement analysis model created successfully')
          
          # Create activity adaptation model
          logger.info('Creating activity adaptation model...')
          adaptation_model = {'weights': np.random.rand(10)}
          joblib.dump(adaptation_model, '/app/app/models/activity_adaptation.joblib')
          logger.info('Activity adaptation model created successfully')
          
          # Create activity assessment model
          logger.info('Creating activity assessment model...')
          assessment_model = {'weights': np.random.rand(10)}
          joblib.dump(assessment_model, '/app/app/models/activity_assessment.joblib')
          logger.info('Activity assessment model created successfully')
          
      except Exception as e:
          logger.error(f'Error creating models: {str(e)}')
          raise
      "
      
      # Run database migrations
      echo "Running database migrations..."
      python3.10 -m alembic upgrade head
      
      # Seed the database
      echo "Seeding database with initial data..."
      python3.10 -m scripts.seed_data
      
      # Create static directory structure
      echo "Creating static directory structure..."
      mkdir -p /app/static
      echo "Static directory created at /app/static"
      
      # Copy static files
      echo "Copying static files..."
      if [ -d "app/static" ]; then
        echo "Source directory exists, contents:"
        ls -la app/static
        cp -rv app/static/* /app/static/
        echo "Files copied successfully"
      else
        echo "ERROR: app/static directory not found"
        exit 1
      fi
      
      # Verify the copy
      echo "Verifying static directory contents:"
      ls -la /app/static
      
      # Set permissions
      chmod -R 755 /app/static
      
      # Create symlink
      ln -sf /app/static static
      
      # Final verification
      echo "Final directory structure:"
      ls -la /app/static
      echo "Models directory contents:"
      ls -la /app/models
    startCommand: |
      echo "Starting application..."
      echo "Current directory: $(pwd)"
      echo "Static directory contents:"
      ls -la /app/static
      echo "Models directory contents:"
      ls -la /app/models
      python3.10 -m gunicorn --config gunicorn.conf.py wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONPATH
        value: .
      - key: APP_ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: API_PORT
        value: 8000
      - key: METRICS_PORT
        value: 8001
      - key: WEBSOCKET_PORT
        value: 8002
      - key: LOG_LEVEL
        value: info
      - key: LOG_DIR
        value: /tmp/faraday-ai/logs
      - key: MODEL_DIR
        value: /app/models
      - key: VERSION
        value: 0.1.0
      - key: WORKERS
        value: 8
      - key: ALLOWED_HOSTS
        value: faraday-ai.onrender.com,localhost,127.0.0.1,faraday-ai.com,www.faraday-ai.com
      - key: CORS_ORIGINS
        value: https://faraday-ai.com,https://www.faraday-ai.com
      - key: RATELIMIT_STORAGE_URL
        value: memory://
      - key: RATELIMIT_DEFAULT
        value: "100/minute"
      - key: RATELIMIT_STRATEGY
        value: fixed-window
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MINIO_URL
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        value: faraday-media
      - key: ENABLE_METRICS
        value: "true"
      - key: DEBUG
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90
      targetCPUPercent: 90
