services:
  - type: web
    name: faraday-ai
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /tmp/faraday-ai/logs
      chmod -R 777 /tmp/faraday-ai/logs
      mkdir -p static/images
      chmod -R 755 static
    startCommand: gunicorn --config gunicorn.conf.py main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: APP_ENVIRONMENT
        value: production
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: info
      - key: LOG_DIR
        value: /tmp/faraday-ai/logs
      - key: VERSION
        value: 0.1.0
      - key: WORKERS
        value: 4
      - key: ALLOWED_HOSTS
        value: faraday-ai.onrender.com,localhost,127.0.0.1
      - key: CORS_ORIGINS
        value: https://faraday-ai.onrender.com
      - key: RATELIMIT_STORAGE_URL
        value: memory://
      - key: RATELIMIT_DEFAULT
        value: "100/minute"
      - key: RATELIMIT_STRATEGY
        value: fixed-window
    healthCheckPath: /test
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline';"
