services:
  - type: web
    name: faraday-ai
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p $PWD/app/static/images
      cp -f app/static/images/coming-soon.png $PWD/app/static/images/ || true
      ls -la $PWD/app/static/images/
    startCommand: cd $PWD && PYTHONPATH=$PWD uvicorn app.main:app --host 0.0.0.0 --port $PORT --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: .
      - key: APP_ENVIRONMENT
        value: production
      - key: DEBUG
        value: true
      - key: LOG_LEVEL
        value: debug
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /*
        destination: /
    envVars:
      - key: BETA_VERSION
        value: 1.0.0
      - key: DEPLOYMENT_STAGE
        value: beta
      - key: MSCLIENTID
        sync: false
      - key: MSCLIENTSECRET
        sync: false
      - key: MSTENANTID
        sync: false
      - key: REDIRECT_URI
        value: https://faraday-ai.com/auth/callback
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GPT_MODEL
        value: gpt-4-turbo-preview
      - key: MAX_TOKENS
        value: 2000
      - key: TEMPERATURE
        value: 0.7
      - key: ENABLE_TWILIO
        value: true
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: TWILIO_VOICE_URL
        value: https://faraday-ai.com/voice
      - key: TWILIO_WEBHOOK_URL
        value: https://faraday-ai.com/api/v1/twilio/webhook
      - key: TWILIO_STATUS_CALLBACK
        value: https://faraday-ai.com/api/v1/twilio/status
      - key: ENABLE_GOOGLE_CLOUD
        value: false
      - key: SCOPE
        value: User.Read Mail.Read Files.ReadWrite.All