services:
  - type: web
    name: faraday-ai
    runtime: python
    region: oregon
    plan: pro-4gb
    buildCommand: |
      python3.10 -m pip install -r requirements.txt
      
      # Create models directory
      echo "Creating models directory..."
      mkdir -p models
      
      # Create placeholder model file
      echo "Creating placeholder model file..."
      touch models/movement_analysis.h5
      
      # Run database migrations
      echo "Running database migrations..."
      python3.10 -m alembic upgrade head
      
      # Seed the database
      echo "Seeding database with initial data..."
      python3.10 -m scripts.seed_data
      
      mkdir -p /tmp/faraday-ai/logs
      chmod -R 777 /tmp/faraday-ai/logs
      
      # Debug information
      echo "Current working directory: $(pwd)"
      echo "Directory contents:"
      ls -la
      
      # Create static directory structure
      echo "Creating static directory structure..."
      mkdir -p /app/static
      echo "Static directory created at /app/static"
      
      # Copy static files
      echo "Copying static files..."
      if [ -d "app/static" ]; then
        echo "Source directory exists, contents:"
        ls -la app/static
        cp -rv app/static/* /app/static/
        echo "Files copied successfully"
      else
        echo "ERROR: app/static directory not found"
        exit 1
      fi
      
      # Verify the copy
      echo "Verifying static directory contents:"
      ls -la /app/static
      
      # Set permissions
      chmod -R 755 /app/static
      
      # Create symlink
      ln -sf /app/static static
      
      # Final verification
      echo "Final directory structure:"
      ls -la /app/static
    startCommand: |
      echo "Starting application..."
      echo "Current directory: $(pwd)"
      echo "Static directory contents:"
      ls -la /app/static
      python3.10 -m gunicorn --config gunicorn.conf.py wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONPATH
        value: .
      - key: APP_ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: API_PORT
        value: 10000
      - key: METRICS_PORT
        value: 10001
      - key: WEBSOCKET_PORT
        value: 10002
      - key: LOG_LEVEL
        value: info
      - key: LOG_DIR
        value: /tmp/faraday-ai/logs
      - key: VERSION
        value: 0.1.0
      - key: WORKERS
        value: 4
      - key: ALLOWED_HOSTS
        value: faraday-ai.onrender.com,localhost,127.0.0.1,faraday-ai.com,www.faraday-ai.com
      - key: CORS_ORIGINS
        value: https://faraday-ai.com,https://www.faraday-ai.com
      - key: RATELIMIT_STORAGE_URL
        value: memory://
      - key: RATELIMIT_DEFAULT
        value: "100/minute"
      - key: RATELIMIT_STRATEGY
        value: fixed-window
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: MINIO_URL
        sync: false
      - key: MINIO_ACCESS_KEY
        sync: false
      - key: MINIO_SECRET_KEY
        sync: false
      - key: MINIO_BUCKET
        value: faraday-media
      - key: ENABLE_METRICS
        value: "true"
      - key: DEBUG
        value: "false"
    healthCheckPath: /health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 90
      targetCPUPercent: 90
