from setuptools import setup, find_packages

setup(
    name="faraday-ai",
    version="0.1.0",
    description="Faraday AI - An AI-powered physical education and learning platform",
    author="Faraday AI Team",
    packages=find_packages(),
    include_package_data=True,
    package_data={
        'app': ['*.json', '*.yaml', '*.yml'],
        'app.services.physical_education': ['*.json', '*.yaml', '*.yml'],
    },
    install_requires=[
        "fastapi",
        "uvicorn",
        "gunicorn",
        "tensorflow",
        "opencv-python",
        "redis",
        "minio",
        "prometheus-client",
        "python-multipart",
        "python-jose",
        "passlib",
        "bcrypt",
        "sqlalchemy",
        "psycopg2-binary",
        "alembic",
        "pydantic",
        "python-dotenv",
        "pandas",
        "numpy",
        "plotly",
        "seaborn",
        "matplotlib",
        "networkx",
        "psutil",
        "email-validator",
        "imageio",
        "python-pptx",
        "python-docx",
    ],
    extras_require={
        'dev': [
            "pytest==8.0.1",
            "pytest-asyncio==0.23.5",
            "pytest-cov==4.1.0",
            "black==24.1.1",
            "flake8==7.0.0",
            "mypy==1.8.0",
            "isort==5.13.2",
        ],
        'docs': [
            "sphinx==7.2.6",
            "sphinx-rtd-theme==2.0.0",
        ],
    },
    python_requires=">=3.10",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Topic :: Education",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
) 